title: My Personal Site
email: Cheng-Nan.Liu@utah.edu
description: "Welcome to my personal website!"
baseurl: ""
url: "https://andrewntu.github.io"
theme: minima

navigation:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Publications
    url: /publications/
